import pywhatkit
import pandas as pd
import imp
password = imp.google_p['password']
readme = pd.read_csv("C:\\Users\\krish\\Downloads\\email - Sheet1 (1).csv")
for i in range(len(readme)):
    name = readme['name'][i]
    mid  = readme['mid'][i]
    pywhatkit.mail.send_mail(email_sender="krishnatanna41@gmail.com",
                             password=password,subject="youtube",
                             message=f"hello {name},\nThis message is autogenerated!",
                             email_receiver=mid)
    