import pywhatkit # use - pip install pywhatkit 
import pandas as pd # use - pip install pandas
import imp # this is custom python file kindly check whole video.
password = imp.google_p['password']
readme = pd.read_csv("your csv file path")
for i in range(len(readme)):
    name = readme['name'][i]
    mid  = readme['mid'][i]
    pywhatkit.mail.send_mail(email_sender="your email id",
                             password=password,subject="youtube",
                             message=f"hello {name},\nThis message is autogenerated!",
                             email_receiver=mid)
    
