import time #Open cmd and paste this and press ENTER key- pip install time 
from turtle import * #Open cmd and paste this and press ENTER key- pip install turtle
import PySimpleGUI as sg #Open cmd and paste this and press ENTER key- pip install pySimpleGUI
sg.theme('Default')
speed("fastest")
def A():
    penup()
    goto(-30, 50)
    pendown()
    pensize(20)
    pencolor("grey")
    forward(130)
    right(45)
    forward(50)
    backward(150)
    right(90)
    forward(150)
    time.sleep(2)
    resetscreen()
def R():
    penup()
    goto(-30, 50)
    pendown()
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    goto(-30, 50)
    right(-90)
    circle(-50, 180, 100)
    penup()
    goto(-27, -44)
    left(135)
    pendown()
    forward(70)
    time.sleep(2)
    resetscreen()
def M():
    penup()
    goto(-30, 50)
    pendown()
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    goto(-30, 50)
    goto(20, -20)
    goto(65, 50)
    goto(65, -100)
    time.sleep(2)
    resetscreen()
def B():
    penup()
    goto(-30, 50)
    pendown()
    pensize(20)
    color("grey")
    circle(80, 180)
    left(90)
    forward(145 * 2)
    left(90)
    circle(80, 180)
    time.sleep(2)
    resetscreen()
def C():
    penup()
    goto(-30, 50)
    pendown()
    pensize(10)
    pencolor("grey")
    right(180)
    circle(50, 180)
    time.sleep(2)
    resetscreen()
def D():
    penup()
    goto(-30, 50)
    pendown()
    pensize(10)
    pencolor("grey")
    right(90)
    forward(200)
    penup()
    goto(-30, 50)
    pendown()
    right(-90)
    circle(-100, 180)
    time.sleep(2)
    resetscreen()
def E():
    penup()
    setpos(-30, 50)
    pendown()
    pensize(10)
    pencolor("grey")
    forward(100)
    backward(100)
    right(90)
    forward(100)
    left(90)
    forward(100)
    backward(100)
    right(90)
    forward(100)
    left(90)
    forward(100)
    time.sleep(2)
    resetscreen()
def F():
    pencolor("grey")
    penup()
    setpos(-30, 50)
    pendown()
    pensize(10)
    forward(100)
    backward(100)
    right(90)
    forward(100)
    left(90)
    forward(100)
    backward(100)
    right(90)
    forward(100)
    time.sleep(2)
    resetscreen()
def G():
    pencolor("grey")
    penup()
    goto(-30, 50)
    pendown()
    pensize(10)
    right(180)
    circle(50, 180)
    left(90)
    forward(50)
    goto(-50, 0)
    right(90)
    forward(50)
    right(90)
    forward(50)
    time.sleep(2)
    resetscreen()
def H():
    pencolor("grey")
    penup()
    goto(-30, 50)
    pendown()
    pensize(10)
    right(90)
    forward(200)
    goto(-30, -50)
    goto(50, -50)
    goto(50, 50)
    goto(50, -140)
    time.sleep(2)
    resetscreen()
def I():
    pencolor("grey")
    penup()
    goto(-30, 50)
    pendown()
    pensize(10)
    forward(100)
    backward(200)
    forward(100)
    right(90)
    forward(150)
    left(90)
    forward(100)
    backward(200)
    time.sleep(2)
    resetscreen()
def J():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    forward(10)
    right(90)
    forward(150)
    circle(-50, 180)
    time.sleep(2)
    resetscreen()
def K():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    goto(-30, -20)
    left(45)
    forward(100)
    goto(-30, -20)
    left(90)
    forward(100)
    time.sleep(2)
    resetscreen()
def L():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    right(-90)
    forward(70)
    time.sleep(2)
    resetscreen()

def N():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    goto(-30, 50)
    goto(50, -90)
    goto(50, 50)
    time.sleep(2)
    resetscreen()
def O():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    circle(100, None, 100)
    time.sleep(2)
    resetscreen()
def P():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(150)
    goto(-30, 50)
    circle(50, None, 100)
    time.sleep(2)
    resetscreen()
def Q():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    circle(50, None, 100)
    right(45)
    forward(30)
    time.sleep(2)
    resetscreen()
def S():
    pencolor("grey")
    pensize(10)
    penup()
    setpos(50, 180)
    pendown()
    forward(30)
    backward(30)
    circle(-90, -185)
    circle(90, -250)
    time.sleep(2)
    resetscreen()
def T():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    forward(100)
    goto(20, 50)
    right(90)
    forward(100)
    time.sleep(2)
    resetscreen()
def U():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(90)
    forward(100)
    circle(50, 180, 100)
    forward(100)
    time.sleep(2)
    resetscreen()
def V():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(65)
    forward(100)
    left(130)
    forward(100)
    time.sleep(2)
    resetscreen()
def W():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(65)
    forward(100)
    left(130)
    forward(100)
    right(120)
    forward(100)
    left(130)
    forward(100)
    time.sleep(2)
    resetscreen()
def X():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(50)
    forward(155)
    penup()
    goto(50, 50)
    right(70)
    pendown()
    forward(150)
    time.sleep(2)
    resetscreen()
def Y():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    right(65)
    forward(100)
    left(130)
    forward(100)
    penup()
    goto(13, -43)
    left(25)
    pendown()
    backward(100)
    time.sleep(2)
    resetscreen()
def Z():
    pencolor("grey")
    pensize(10)
    penup()
    goto(-30, 50)
    pendown()
    forward(100)
    right(130)
    forward(130)
    left(130)
    forward(100)
    time.sleep(2)
    resetscreen()
def notice():
    penup()
    goto(-370,-300)
    pendown()
    write("click on screen to exit!", font=("normal",  10, "bold"))
    time.sleep(1)
    resetscreen()

k = [[sg.Text('Enter Your Name:', size =(15, 1)), sg.InputText()],[sg.Submit(),sg.Cancel()]]
w = sg.Window("",k)
l = w.read()
user = str(l[1][0])
user = user.upper()
w.close()
function_map = {
    'A': A,
    'B': B,
    'C': C,
    'D': D,
    'E': E,
    'F': F,
    'G': G,
    'H': H,
    'I': I,
    'J': J,
    'K': K,
    'L': L,
    'M': M,
    'N': N,
    'O': O,
    'P': P,
    'Q': Q,
    'R': R,
    'S': S,
    'T': T,
    'U': U,
    'V': V,
    'W': W,
    'X': X,
    'Y': Y,
    'Z': Z,
}
time.sleep(2)
try:
    for i in user:
        function_map[i]()
except Exception as e:
    sg.popup_annoying("OOPS!, you entered number in input.")
write(user,font=("normal", 50, "bold"),align="center")
exitonclick()
